### ISSUE TITLE
Track mission progress

### ISSUE THREAD

**Issue by nikalc** [DIT112-V21/group-09#25]
As a user I want to be able to track the mission progress so that I see progress of each steps.

Acceptance Criteria:
Scenario: The user has details about the mission progress shown on the frontend application and is able to evaluate the results in real time. 

Given that the user has sent a mission to be executed to the emulator
When the user monitors Mission control page
Then the rover's mission updates are easily seen or displayed for the current mission

**Comment by axe007** [comment]
More relevant to Mission control section. Re-assigning to Milestone 4.

**Comment by axe007** [comment]
Deferring to Sprint 4 pending mission drive feature completion.
