### ISSUE TITLE
Retrieve data after software restart

### ISSUE THREAD

**Issue by nikalc** [DIT112-V21/group-09#26]
As a user I want to be able to access data even after the software is restarted.

Acceptance Criteria:
Scenario: The user has restarted the software and wants to retrieve and access the data stored prior to the restart

Given that the user has restarted the software
When the user wants to retrieve the data prior to the restart
Then the data is stored in a database

**Comment by axe007** [comment]
Re-assigning to new data persistence milestone.

**Comment by axe007** [comment]
We need to re-evaluate description and acceptance criteria to describe the feature more precisely.
