### ISSUE TITLE
Save and load missions

### ISSUE THREAD

**Issue by nikalc** [DIT112-V21/group-09#27]
### User store
As a user I want to be able to save my mission and load them from the database using my user account

### Acceptance Criteria:
Scenario: The user logged in with the account and wants to save/load a mission

Given that the user has logged in with their account
When the user opens the Mission control page
Then the user is able to choose to save a mission or load from saved missions.

**Comment by axe007** [comment]
More relevant to Mission control section. Re-assigning to Milestone 4.

**Comment by axe007** [comment]
Deferring to Sprint 4 pending database and setting page completion.
