### ISSUE TITLE
1.1 Frontend application layout

### ISSUE THREAD

**Issue by nikalc** [DIT112-V21/group-09#28]
As a user, I want to be able to launch the frontend application and access the generic layout so that I can use the application directly

Scenario: The user launches the frontend application and automatically enters the home page where the generic layout is located

Acceptance Criteria:
Given that the user has launched the frontend application, 
When the page is fully loaded
Then the generic layouts is displayed and ready for usage

**Comment by axe007** [comment]
Update layout and merged the PR.
