### ISSUE TITLE
1.4 Frontend centered functionalities

### ISSUE THREAD

**Issue by nikalc** [DIT112-V21/group-09#31]
As a user I want to be able to have all functionalities centered on the frontend application so I can navigate more easily.

Scenario: The user enters the home page and is able to navigate through the user interface via the frontend application without having to use another platform besides the frontend application

Acceptance Criteria:
Given that i have entered the frontend application
When i click any of the button displayed
Then the buttons are all connected to the frontend application

**Comment by axe007** [comment]
It seems that this issue has been completed through several other issue completions. We may need to setup a unit test to verify. Closing for now.
