### ISSUE TITLE
Instructions for users

### ISSUE THREAD

**Issue by nikalc** [DIT112-V21/group-09#33]
As a user I want instructions of application usage to be shown on the frontend application so that I can easily look up instructions

Scenario: The user is using the application and Is uncertain about some functionalities displayed on the frontend application

Given that i have navigated and found the instructions on the frontend application
When i click to read the instructions
Then instructions are sorted with the most basic functions first decrementing to more advanced

**Comment by axe007** [comment]
Too early to start working on the user instructions. Bumping back to Sprint #3.

**Comment by axe007** [comment]
## Change:
We continue working on this into Sprint 4.

## Completed:
- Windows and macOS setup guides are in good shape. Needs minor revisions only.
- Manual control page guide is evolving.

## Pending:
- Mission control page guide will start once we have mission driving part done.
- Settings and user management guide will be done when respective issues are complete.
