### ISSUE TITLE
Persistent settings page

### ISSUE THREAD

**Issue by axe007** [DIT112-V21/group-09#64]
### User story 
As a user, I want to access frontend, user, MQTT connection parameter and other related settings and modify as needed.

### Acceptance Criteria
Scenario: The user access Settings page.

- Given that I have accessed Settings page through main navigation
- When I open Settings page
- Then I should be able to review all settings with UI patterns, modify and save as needed. Escape to cancel changes must be provided.

**Comment by axe007** [comment]
Extending this issue into Sprint 3 as it is linked to database and user profile stuff.

**Comment by axe007** [comment]
Reassigning to the new Milestone, as it better packages those bulk of user stories and tasks.

**Comment by kam56** [comment]
- [ TASK ] Update the current settings page 
- [ TASK ] Persist settings data into the database

**Comment by axe007** [comment]
Pushing back into Sprint 4 to finalize.
