### ISSUE TITLE
Mission step driving

### ISSUE THREAD

**Issue by axe007** [DIT112-V21/group-09#73]
## User story - In mission, mission step driving with obstacle avoidance
As a user I want the rover to drive as instructed within mission step parameters while avoiding potential obstacles automatically so that I can complete a mission.

### Acceptance Criteria
Scenario: The SmartRover drives in the given direction and avoid an obstacle during a mission.

- Given that the SmartRover is driving to complete a step
- When obstacle is in direct collision course with the rover
- Then the rover must automatically take evasive actions and resume its original course and heading.

**Comment by kam56** [comment]
Since the dependent issue (https://github.com/DIT112-V21/group-09/issues/27)  and persisting data to the database took longer than expected, I move this issue to the next sprint.
