### ISSUE TITLE
User registration and login

### ISSUE THREAD

**Issue by axe007** [DIT112-V21/group-09#88]
### User story
As a user, I want to be able to register a new account and login into the Frontend app.

### Acceptance Criteria
Scenario: The user enters Frontend app, and register a new account.

- Given that I have access Frontend app
- When I enter my details in the Registration page
- Then I can create a new account and login with the account.

**Comment by kam56** [comment]
For this user story, will we have the registration or login option only on the setting page? or as alongside the rest of the menus on the home page as well? 

- As we discussed before, it is better to have the login page as a modal "window", not a separate page.

**Comment by axe007** [comment]
We made good progress here. Pushing into Sprint 4 to finalize in good shape.
