### ISSUE TITLE
1.5 Feedback section

### ISSUE THREAD

**Issue by OneMoreOreo** [DIT112-V21/group-09#9]
As a user I want to be able to get feedback/alerts if there is any error when inputting data, so that I can use the software correctly.

Acceptance criteria: Frontend app has console/feedback section to display any response or messages from the Rover.

**Comment by kam56** [comment]
Markus (@OneMoreOreo ), I have added a section in the Drive page besides info board. we can implement this user story in that section. I will let you know when I am done with the rest of the sections. then you can continue working on it.
